config/routes.rb
Rails.application.routes.draw do
  resources :stored_urls, only: [:create]

  root to: 'visitors#index'

  post 'call' => 'twilio#call'
  post 'connect' => 'twilio#connect'
  get 'twilio' => 'twilio#index'
  post 'voice' => 'twilio#voice'
  get 'generate_call' => 'twilio#generate_call'
  get 'map' => 'visitors#map'
end

app/models/bvm_location.rb
class BvmLocation < ActiveRecord::Base
end

app/models/canada_location.rb
class CanadaLocation < ActiveRecord::Base
end

app/models/contact.rb
# Simple model to handle validation
class Contact
  include ActiveModel::Validations
  attr_accessor :phone
  validates_presence_of :phone
  validates :phone, :presence => true
end

app/models/n2_ads.rb
class N2Ads < ActiveRecord::Base
end

app/models/stored_url.rb
class StoredUrl < ActiveRecord::Base
	validates :link, presence: true, uniqueness: { case_sensitive: false }, format: {
	with: /\A(?:[a-zA-Z]+\.){0,1}(?:[a-zA-Z0-9][a-zA-Z0-9-]+){1}(?:\.[a-zA-Z]{2,6})+\z/}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/webhookify.rb
# Written by Carter Rabasa - @CarterRabasa to easily render TwiML enpoints.
module Webhookify
	extend ActiveSupport::Concern

	def set_header
      response.headers["Content-Type"] = "text/xml"
	end

	def render_twiml(response)
      render text: response.text
	end

end

app/controllers/stored_urls_controller.rb
class StoredUrlsController < ApplicationController
  def create
    added = 0
    if params[:urls].present?
      params[:urls].each do |url|
        store_url = StoredUrl.new(link: url)
        added += 1 if store_url.save
      end
      message = "Added Urls: #{added}"
    else
      message = "No Url Found"
    end
    render json: {message: message}
  end
end

app/controllers/twilio_controller.rb
require 'twilio-ruby'

class TwilioController < ApplicationController
  # Before we allow the incoming request to connect, verify
  # that it is a Twilio request
  before_filter :authenticate_twilio_request, :only => [
    :connect
  ]

  # Define our Twilio credentials as instance variables for later use
  @@twilio_sid = "AC748f6e8ec236fdebf6900e7f76cd7aa7"
  @@twilio_token = "8f4a28862c85ed016f957e9fc16c1893"

 @@twilio_app_sid = "AP3df9910c187dc82093ca5fd20e634b3b"

  @@twilio_number = "+15109965685"
  # Render home page
  def index
  	render 'index'
  end
def generate_call
    capability = Twilio::Util::Capability.new @@twilio_sid, @@twilio_token
    # Create an application sid at twilio.com/user/account/apps and use it here
    capability.allow_client_outgoing @@twilio_app_sid
    capability.allow_client_incoming 'adnan'
    @token = capability.generate
  end
def voice
    number = params[:PhoneNumber]
    response = Twilio::TwiML::Response.new do |r|
        # Should be your Twilio Number or a verified Caller ID
        r.Dial :callerId => @@twilio_number do |d|
            # Test to see if the PhoneNumber is a number, or a Client ID. In
            # this case, we detect a Client ID by the presence of non-numbers
            # in the PhoneNumber parameter.
            if /^[\d\+\-\(\) ]+$/.match(number)
                d.Number(CGI::escapeHTML number)
            else
                d.Client @@twilio_number
            end
        end
    end
    response.text
  end

  # Hande a POST from our web form and connect a call via REST API
  def call
    contact = Contact.new
    contact.phone = params[:phone]
   
    # Validate contact
    if contact.valid?

      @client = Twilio::REST::Client.new @@twilio_sid, @@twilio_token
      # Connect an outbound call to the number submitted
      @call = @client.account.calls.create(
        :from => @@twilio_number,
        :to => contact.phone,
        :url => "#{root_url}connect" # Fetch instructions from this URL when the call connects
      )

      # Lets respond to the ajax call with some positive reinforcement
      @msg = { :message => 'Phone call incoming!', :status => 'ok' }

    else

      # Oops there was an error, lets return the validation errors
      @msg = { :message => contact.errors.full_messages, :status => 'ok' }
    end
    respond_to do |format|
      format.json { render :json => @msg }
    end
  end

  # This URL contains instructions for the call that is connected with a lead
  # that is using the web form.  These instructions are used either for a
  # direct call to our Twilio number (the mobile use case) or 
  def connect
    # Our response to this request will be an XML document in the "TwiML"
    # format. Our Ruby library provides a helper for generating one
    # of these documents
    response = Twilio::TwiML::Response.new do |r|
      r.Say 'If this were a real click to call implementation, you would be connected to an agent at this point.', :voice => 'alice'
    end
    render text: response.text
  end


  # Authenticate that all requests to our public-facing TwiML pages are
  # coming from Twilio. Adapted from the example at 
  # http://twilio-ruby.readthedocs.org/en/latest/usage/validation.html
  # Read more on Twilio Security at https://www.twilio.com/docs/security
  private
  def authenticate_twilio_request
    twilio_signature = request.headers['HTTP_X_TWILIO_SIGNATURE']

    # Helper from twilio-ruby to validate requests. 
    @validator = Twilio::Util::RequestValidator.new(@@twilio_token)
 
    # the POST variables attached to the request (eg "From", "To")
    # Twilio requests only accept lowercase letters. So scrub here:
    post_vars = params.reject {|k, v| k.downcase == k}
 
    is_twilio_req = @validator.validate(request.url, post_vars, twilio_signature)
 
    unless is_twilio_req
      render :xml => (Twilio::TwiML::Response.new {|r| r.Hangup}).text, :status => :unauthorized
      false
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
	def index
		@urls = StoredUrl.order("updated_at DESC")
	end

	def map
		require "json"

		#-------------->N2ADS
		n2ad_limit = 301
		n2ad_offset = (params[:page].blank? ? 0 : (params[:page].to_i - 1) * n2ad_limit)
		n2ads = N2Ads.where('lat <> ? AND lat IS NOT NULL AND lng <> ? AND lng IS NOT NULL', '', '').limit(n2ad_limit).offset(n2ad_offset)
		collection_n2ads = n2ads.map do |n2ad|
		   { lat: n2ad.lat, lng: n2ad.lng, city: n2ad.city.to_s, infowindow: "Primary Interviewer: <strong>#{n2ad.primary_interviewer.to_s}</strong><br>Secondary Interviewer: <strong>#{n2ad.secondary_interviewer.present? ? n2ad.secondary_interviewer : 'N/A'}</strong><br>Region: <strong>#{n2ad.region}</strong>",  icon: 'marker-red.png' }
		end

		#-------------->Canada Locations
		canada_locations = CanadaLocation.select(:lat, :lng, :city, :state).where('lat <> ? AND lat IS NOT NULL AND lng <> ? AND lng IS NOT NULL', '', '')
		collection_canada = canada_locations.map do |canada_location|
		   { lat: canada_location.lat, lng: canada_location.lng, city: canada_location.city.to_s, infowindow: "Location: <strong>#{canada_location.city}, #{canada_location.state}</strong>",  icon: 'marker-blue.png'}
		end

		#-------------->Bvm Location
		bvm_limit = 500
		bvm_offset = (params[:page].blank? ? 0 : (params[:page].to_i - 1) * bvm_limit)
		bvm_locations = BvmLocation.select(:lat, :lng, :location).where('lat <> ? AND lat IS NOT NULL AND lng <> ? AND lng IS NOT NULL', '', '').limit(bvm_limit).offset(bvm_offset)
		collection_bvm = bvm_locations.map do |bvm_location|
		   { lat: bvm_location.lat, lng: bvm_location.lng, infowindow: "Location: <strong>#{bvm_location.location}</strong>",  icon: 'marker-blue.png'}
		end
		
		merged_hash = collection_n2ads + collection_canada + collection_bvm
		@final_hash = merged_hash.to_json
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stored_urls_helper.rb
module StoredUrlsHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Test Application" %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Test Application" %>">
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>


</head>
<body>
  <%= yield %>
</body>
</html>

app/views/twilio/generate_call.html.erb
<script type="text/javascript"
      src="//static.twilio.com/libs/twiliojs/1.2/twilio.min.js"></script>
    <script type="text/javascript"
      src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js">
    </script>
    <link href="http://static0.twilio.com/packages/quickstart/client.css"
      type="text/css" rel="stylesheet" />
    <script type="text/javascript">
 
    Twilio.Device.setup("<%= token %>", {debug: true});
 
      Twilio.Device.ready(function (device) {
        $("#log").text("Ready");
      });
 
      Twilio.Device.error(function (error) {
        $("#log").text("Error: " + error.message);
      });
 
      Twilio.Device.connect(function (conn) {
        $("#log").text("Successfully established call");
      });
 
      Twilio.Device.disconnect(function (conn) {
        $("#log").text("Call ended");
      });
 
      Twilio.Device.incoming(function (conn) {
        $("#log").text("Incoming connection from " + conn.parameters.From);
        // accept the incoming connection and start two-way audio
        conn.accept();
      });
 
      function call() {
        // get the phone number to connect the call to
        params = {"PhoneNumber": $("#number").val()};
        Twilio.Device.connect(params);
      }
 
      function hangup() {
        Twilio.Device.disconnectAll();
      }
    </script>
  
    <button class="call" onclick="call();">
      Call
    </button>
 
    <button class="hangup" onclick="hangup();">
      Hangup
    </button>
 
    <input type="text" id="number" name="number"
      placeholder="Enter a phone number to call"/>
 
    <div id="log">Loading pigeons...</div>

app/views/twilio/index.erb
<!DOCTYPE html>
<html>
	<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	  <title>Click To Call Tutorial</title>
    <link rel="icon" type="image/png" href="/img/favicon.png">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css" type="text/css">
    <%= stylesheet_link_tag 'application' %>
  </head>
  <body>
    <div class="container">
      <h1>Click To Call</h1>
      <p>Click To Call converts your website's users into engaged customers by creating an easy way for your customers to contact your sales and support teams right on your website.</p>
      <p>Here's an example of how it's done!</p>
      <hr>
      <div class="row">
        <div class="col-md-12">
          <form id="contactform" role="form" action="#" method="POST">
            <div class="form-group">
              <h3>Call Sales</h3>
              <p class="help-block">
                Are you interested in impressing your friends and confounding your enemies? Enter your phone number below, and our team will contact you right away.
              </p>
            </div>
            <div class="form-group">
              <input class="form-control" type="text" name="phone" id="phoneNumber" placeholder="(651) 555-7889">
            </div>
            <button type="submit" class="btn btn-default">Contact Sales</button>
          </form>

        </div>
      </div>
	  </div><!-- /page -->
	</body>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</html>

app/views/twilio/index.haml
!!!  
%html  
  %head  
    %title Click To Call Tutorial
    %link{:rel => "icon", :type => "image/png", :href => "/img/favicon.png"}
    %link{:rel => "stylesheet", :href => "//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css"}
    %link{:rel => "stylesheet", :href => "//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css", :type => "text/css"}
    = stylesheet_link_tag 'application', :media => 'all'
    
  %body
    .container
      %h1 Click To Call
      %p
        Click To Call converts your website's users into engaged customers by creating an easy way for your customers to contact your sales and support teams right on your website.

      %p Here's an example of how it's done!

      %hr

      // C2C contact form
      .row
        .col-md-12
          %form{:id => "contactform", :role => 'form', :action => '#', :method => 'POST'}
            .form-group
              %h3 Call Sales
              %p.help-block
                Are you interested in impressing your friends and confounding your enemies? Enter your phone number below, and our team will contact you right away.
            .form-group
              %input.form-control{:type =>'text', :name => 'phone', :id => 'phoneNumber', :placeholder => '(651) 555-7889'}
            %button{ :type => 'submit', :class => 'btn btn-default'} Contact Sales
            
  = javascript_include_tag 'application', 'data-turbolinks-track' => true

app/views/visitors/index.html.erb
<div class="form_section">
		<p class="bg-danger" id="message"></p>
		<div class="form-group">
			<%= text_field_tag :url, '', placeholder: 'Enter URL', class: 'form-control' %>
		</div>
		<ul id="urls">
			<% @urls.each do |url| %>
				<li><%= url.link %></li>
			<% end %>
		</ul>
	</div>
<div>

<script type="text/javascript">
	urls = [<%= raw(@urls.collect{|url| "\"#{url.link}\""}.join(', ')) %>];
	$('#url').keypress(function(e) {
			$('#message').html('');
	    if(e.which == 13) {
	    	checkOrAddUrl($(this), $('#urls'), $('#message'));
	    }
	});
	setInterval(function() {checkAndSyncUrls('#urls', '<%= stored_urls_path %>')}, 15000);
</script>

app/views/visitors/map.html.erb
<div style="margin: 30px 15px 0;">
	<ul class="nav nav-pills">
		<% 5.times do |t| %>
		  <li role="presentation" class="<%= "active" if (params[:page].blank? && t == 0) || params[:page].to_i == t + 1 %>">
		  	<%= link_to "Set #{t+1}", map_path(page: t + 1) %>
		  </li>
	  <% end %>
	</ul>
</div>


<main role="main">
	<div id="sidebar_builder" style='width: 100%; height: 600px;'></div>
</main>

<div id='sidebar_container'>
</div>

<script type="text/javascript">
	$(document).ready(function(){
		handler = Gmaps.build('Google');
		var markers;
		handler.buildMap({ internal: {id: 'sidebar_builder'}}, function(){

			json_array = <%= @final_hash.html_safe %>;

			var markers = handler.addMarkers(json_array);

			_.each(json_array, function(json, index){
				json.marker = markers[index];
				json.marker.serviceObject.icon = json.icon;
			});

			handler.bounds.extendWith(markers);
			handler.fitMapToBounds();
		});
	});
</script>